version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@dbpruebas_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=<usr>
      - spring.datasource.password=<pwd>
    restart: always